### ISSUE TITLE
What is happening when the EU is 0?

### ISSUE THREAD

**Issue by Roberyan** [lingchen0331/UQ_ICL#2]
I am trying your pipeline for mamba model to see its uncertainty, but weird things happen that the mamba always has The same AU with EU as 0.( on financial data) how come do this happen? The transformer-based model is normal, all I change is input a different model.

**Comment by lingchen0331** [comment]
Hi, I only tested the code with LLaMA and OPT models, not really sure how the algorithm behaves with S4 models (Mamba). Can you check whether Mamba keeps a finite token set and returns probabilities for all tokens?

If the AU are all the same and EU is 0, it basically means the model returns the same thing no matter how you change the demonstrations.
