### ISSUE TITLE
Confused about the inconsistency between the article and the code

### ISSUE THREAD

**Issue by GuoCheng12** [lingchen0331/UQ_ICL#4]
Thanks for your work, but when I checked the code, I found that the method of calculating EU and AU in the code seems to be different from the method in the article. The method of calculating EU in the article is to calculate the entropy of the output under the same model parameters for different contexts, and the calculation of AU is through TU-EU, but there seems to be no corresponding process in the code. Instead, the calculation of AU can be calculated by calculating the entropy of the category probability obtained from different contexts, and the calculation of EU is TU-AU.
I am very confused as to whether there is something wrong with my understanding. I look forward to your reply.

**Comment by wangyifei0047** [comment]
The same question as  [GuoCheng12](https://github.com/GuoCheng12)

**Comment by lingchen0331** [comment]
Sorry for the confusion, you can regard AU as EU (and vice versa) in the code. We made a mistake with the variable name.
